### ISSUE TITLE
Nodes missing

### ISSUE THREAD

**Issue by specblades** [Zuellni/ComfyUI-ExLlama-Nodes#12]
There are no nodes after install (through comfy manager and manual install). idk no why.

**Comment by Zuellni** [comment]
Are you seeing any errors in the console? Sounds like the nodes didn't import because you either didn't install the requirements or aren't using torch-2.1/cu112 and need to install the ExLlamaV2 wheel manually.

**Comment by specblades** [comment]
I checked again
<img width="342" alt="image" src="https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/113993746/4ea1b000-502d-4b37-b597-8f532b64f6a3">

**Comment by specblades** [comment]
Dunno. I install exllamav2-0.0.9+cu121-cp310-cp310-win_amd64.whl but still getting error.
I need exactly cp311?

**Comment by Zuellni** [comment]
You need the wheel matching your ComfyUI install. If your Python is 3.11 then cp311, torch 2.1+cuda - 12.1 - cu112, Windows - win_amd64 and so on. Can't really tell you which one you need to install if you don't provide any information.

**Comment by specblades** [comment]
Sure. Im on py310 and i install corresponding version of exllama.

**Comment by Zuellni** [comment]
Make sure you can import exllamav2.
```py
python -c "import exllamav2"
```

If this gives you the following error that means you have the wheel for different cuda version installed:
```
ImportError: DLL load failed while importing exllamav2_ext: The specified module could not be found.
```

You can check your version with:
```py
python -c "import torch; print(torch.version.cuda)"
```
This should display something like `12.1`. If it doesn't that means you're probably not in your ComfyUI environment.

If you see a different error then post the traceback, please.

**Comment by xandix1939** [comment]
`Traceback (most recent call last):
  File "/home/dev/ComfyUI/nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dev/ComfyUI/custom_nodes/ComfyUI-ExLlama-Nodes/__init__.py", line 1, in <module>
    from . import exllama, text
  File "/home/dev/ComfyUI/custom_nodes/ComfyUI-ExLlama-Nodes/exllama.py", line 9, in <module>
    from exllamav2 import (
  File "/home/dev/anaconda3/envs/comfy/lib/python3.11/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/dev/anaconda3/envs/comfy/lib/python3.11/site-packages/exllamav2/model.py", line 17, in <module>
    from exllamav2.cache import ExLlamaV2CacheBase
  File "/home/dev/anaconda3/envs/comfy/lib/python3.11/site-packages/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/home/dev/anaconda3/envs/comfy/lib/python3.11/site-packages/exllamav2/ext.py", line 14, in <module>
    import exllamav2_ext
ImportError: /home/dev/anaconda3/envs/comfy/lib/python3.11/site-packages/exllamav2_ext.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationESsb`

I also get the error and so the nodes are not loaded.

regards,
A

**Comment by Zuellni** [comment]
I understand you're on Linux and your Python is 3.11 not 3.10 according to the above. You didn't say what the commands I listed showed so honestly no idea what this means. You should be able to compile the cuda extension on Linux by installing from pip if the wheels don't work in any case.

**Comment by xandix1939** [comment]
I solved this one.

For the Linux version you should change the requirements.txt file to:

`https://github.com/turboderp/exllamav2/releases/download/v0.0.9/exllamav2-0.0.9-py3-none-any.whl; platform_system == "Linux"`

If anyone is on cutting edge like python 3.12, cuda 12.2, it will just compile it when its called the first time.
(Maybe before you have to uninstall your actual install exllamav2 version via pip)
regards,
A

**Comment by Zuellni** [comment]
Right, from what I understand that's the JIT version, ie the same as `pip install exllamav2`. I'll change it to that in the requirements.
