### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by thinkingjimmy** [Zuellni/ComfyUI-ExLlama-Nodes#20]
Hi, I try to install this node on Linux,

I get this error:

```
Traceback (most recent call last):
  File "/comfyui/nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/comfyui/custom_nodes/ComfyUI-ExLlama-Nodes/__init__.py", line 1, in <module>
    from . import exllama, text
  File "/comfyui/custom_nodes/ComfyUI-ExLlama-Nodes/exllama.py", line 6, in <module>
    from exllamav2 import *
  File "/usr/local/lib/python3.10/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/usr/local/lib/python3.10/site-packages/exllamav2/model.py", line 31, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "/usr/local/lib/python3.10/site-packages/exllamav2/config.py", line 5, in <module>
    from exllamav2.fasttensors import STFile
  File "/usr/local/lib/python3.10/site-packages/exllamav2/fasttensors.py", line 6, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/usr/local/lib/python3.10/site-packages/exllamav2/ext.py", line 250, in <module>
    maybe_set_arch_list_env()
  File "/usr/local/lib/python3.10/site-packages/exllamav2/ext.py", line 43, in maybe_set_arch_list_env
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

Could you tell me how to fix it?

Thanks,
Jimmy

**Comment by Zuellni** [comment]
That sounds like a problem with exllama itself, not the nodes. If executing `python -c "import exllamav2"` also shows the same error you should probably open an issue in the [exllamav2 repo](https://github.com/turboderp/exllamav2). Otherwise please provide more info about how you installed it (wheel? jit?), your system, torch, cuda, etc.
