### ISSUE TITLE
No module named 'exllama_ext'

### ISSUE THREAD

**Issue by Franks001** [Zuellni/ComfyUI-ExLlama-Nodes#3]
** ComfyUI start up time: 2023-09-19 18:59:09.101002

Prestartup times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32725 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from .nodes import Generator, Loader, Previewer
  File "E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\nodes.py", line 6, in <module>
    from exllama.alt_generator import ExLlamaAltGenerator
  File "E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllama\__init__.py", line 1, in <module>
    from . import cuda_ext, generator, model, tokenizer
  File "E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllama\cuda_ext.py", line 9, in <module>
    import exllama_ext
ModuleNotFoundError: No module named 'exllama_ext'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: No module named 'exllama_ext'
### ComfyUI Revision: 1465 [6d3dee9d]

Import times for custom nodes:
   0.3 seconds: E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds (IMPORT FAILED): E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by Zuellni** [comment]
Make sure you have the correct version of ExLlama installed as per the readme.  
Based on your log I assume that would be `cp310-cu118-win_amd64`.  
This should work:
```
pip install -U https://github.com/jllllll/exllama/releases/download/0.0.17/exllama-0.0.17+cu118-cp310-cp310-win_amd64.whl
```

**Comment by Franks001** [comment]
Thanks, it works fine
