### ISSUE TITLE
ImportError: DLL load failed while importing exllamav2_ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by Franks001** [Zuellni/ComfyUI-ExLlama-Nodes#7]
E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --port 8192
Total VRAM 11264 MB, total RAM 32725 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from . import exllama, text
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\exllama.py", line 7, in <module>
    from exllamav2 import ExLlamaV2, ExLlamaV2Cache, ExLlamaV2Config, ExLlamaV2Tokenizer
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\linear.py", line 5, in <module>
    from exllamav2 import ext
  File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\ext.py", line 14, in <module>
    import exllamav2_ext
ImportError: DLL load failed while importing exllamav2_ext: 找不到指定的程序。

Cannot import E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: DLL load failed while importing exllamav2_ext: 找不到指定的程序。

Import times for custom nodes:
   0.2 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8192

**Comment by Zuellni** [comment]
If using prebuilt exllamav2 wheels, update your ComfyUI to the [stable release](https://github.com/comfyanonymous/ComfyUI/releases/latest) with pytorch 2.1-cu121 and install [exllamav2-0.0.5+cu121-cp311-cp311-win_amd64.whl](https://github.com/turboderp/exllamav2/releases/latest). There seems to be an issue with the cu118 wheel.

**Comment by Franks001** [comment]
Thanks, it works fine

**Comment by McSimKammerer** [comment]
Hi!
Cannot get extension to work, similar error message:
```
PS D:\CGI\Comfy\ComfyUI> py main.py
Total VRAM 24564 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\CGI\Comfy\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\CGI\Comfy\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from . import exllama, text
  File "D:\CGI\Comfy\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\exllama.py", line 9, in <module>
    from exllamav2 import (
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\exllamav2\model.py", line 16, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\exllamav2\config.py", line 2, in <module>
    from exllamav2.fasttensors import STFile
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\exllamav2\fasttensors.py", line 5, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\exllamav2\ext.py", line 15, in <module>
    import exllamav2_ext
ImportError: DLL load failed while importing exllamav2_ext: The specified procedure could not be found.

Cannot import D:\CGI\Comfy\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: DLL load failed while importing exllamav2_ext: The specified procedure could not be found.

Import times for custom nodes:
   0.3 seconds (IMPORT FAILED): D:\CGI\Comfy\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
```
I spent almost two days trying to solve this, mostly following intuition, not common sense - I lack knowledge. Can you help me?
Thank you in advance!

**Comment by Zuellni** [comment]
That's not a lot of info to go on. Check your Python version:
```
python -V
```
Torch version:
```
python -c "import torch; print(torch.__version__)"
```
Cuda version:
```
python -c "import torch; print(torch.version.cuda)"
```

If Python shows 3.12, there are no wheels for that. If Torch shows anything above 2.2 there are no wheels for that either. You can either downgrade or compile the extension yourself (which requires MS Build Tools and Cuda Toolkit at the very least). If Torch or Cuda error out or show nothing then you don't have Torch with Cuda installed or are in the wrong environment.

Assuming it outputs Python 3.11.x, Torch 2.1.x, Cuda 12.1 (the latest portable ComfyUI build) you should be fine with the default requirements.txt. If you have Torch 2.2, uncomment the relevant lines. I'll split the requirements into separate files, that might help.

Anything else - you should look for the correct wheel in the [ExLlamaV2 repo](https://github.com/turboderp/exllamav2/releases) and install it. Keep in mind wheels >= 0.0.13 only work with Torch 2.2. Latest one compiled with Torch 2.1 seems to be 0.0.12.

**Comment by McSimKammerer** [comment]
Don't know what I did wrong the previous time (probably installed the wrong .whl).
I'm sorry that I didn't provide enough info in the previous post, here is versions:
```
Python 3.11.8
torch 2.2.0+cu121
```
So, I installed requirements-torch-22.txt, now node is importing without errors.
Thank you for your help, and great node!
